### ISSUE TITLE
Add peak fitting unit tests from first HB2B_1060

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#266]
The data from the first 3 subruns of HB2B_1060 do not currently fit well. Write a unit test to fit these three peaks with a pseudo-Voigt after having (by hand) found the "correct" values. These tests can be [`@pytest.mark.skip`](https://docs.pytest.org/en/latest/skipping.html#skipping-test-functions) so the tests can be used to guide fitting work.

**Comment by Fahima-Islam** [comment]
@peterfpeterson is the data already reduced, and the powder patterns stored as test data? I have not seen any related file either under  `PyRS/data` or `PyRS/tests/data`. Otherwise, I could use script `PyRS/scripts/reduce_HB2B.py` to create a file with the powder patterns for the three subruns, which could be stored under `PyRS/tests/data`.

**Comment by peterfpeterson** [comment]
You have to reduce it yourself. Use `scripts/reduce_HB2B.py /path/to/HB2B_1060.nxs.h5 --project HB2B_1060.h5` to get it.

**Comment by Fahima-Islam** [comment]
@peterfpeterson I need access to HB2B data. I am going to contact Jeff and IT to give me the access.
